/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class be_submanifold_pentelive_Ai */

#ifndef _Included_be_submanifold_pentelive_Ai
#define _Included_be_submanifold_pentelive_Ai
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     be_submanifold_pentelive_Ai
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT jlong JNICALL Java_be_submanifold_pentelive_Ai_init(JNIEnv *, jobject, jintArray, jintArray, jint);
/*
 * Class:     be_submanifold_pentelive_Ai
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_submanifold_pentelive_Ai_privateDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_submanifold_pentelive_Ai
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_submanifold_pentelive_Ai_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_submanifold_pentelive_Ai
 * Method:    toggleCallbacks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_submanifold_pentelive_Ai_toggleCallbacks
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     be_submanifold_pentelive_Ai
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_submanifold_pentelive_Ai_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     be_submanifold_pentelive_Ai
 * Method:    move
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_be_submanifold_pentelive_Ai_move
  (JNIEnv *, jobject, jlong, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
